-- Generated by nwg-displays on 2026-09-23 at 07:10:48. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@200.0",
    position = "4480x0",
    scale = 1,
    vrr = 0
})
