-- Generated by nwg-displays on 2026-09-22 at 11:45:58. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "DP-3",
    mode = "2560x1440@200.0",
    position = "0x0",
    scale = 1,
    mirror = "0",
    vrr = 0
})
