-- Generated by displayctl on 2026-09-27 23:45. Do not edit by hand:
-- displayctl rewrites this file on Keep (previous version: monitors.lua.prev).
-- Kept layout:
--   DP-3: 2560x1440@200.000 at 0,0 scale 1 transform 0
--   eDP-1: off, but only while a monitor it was kept with is connected

-- 1. Every monitor that was ON when kept.
hl.monitor({ output = "DP-3", mode = "2560x1440@200.000", position = "0x0", scale = 1, transform = 0 })

-- 3. Laptop panel(s) OFF only while a monitor the layout was kept with is
--    connected and on. Safety layers (see docs/hyprland-persistence.md):
--    a) monitor.removed decides from the EVENT's own data: a kept-with (or
--       unidentifiable) monitor gone -> panel ON directly, and it's
--       remembered as gone for GONE_TTL s, because hl.get_monitors can
--       still list it for a few seconds. If the event object has no
--       description, its port is remembered instead ("port:DP-3"); if it
--       has neither, every kept-with monitor counts as gone ("*");
--    b) "never zero screens": after every load, event and re-check, if no
--       real monitor is on (FALLBACK/headless don't count) -> panel ON;
--    c) delayed re-checks after loads and events, reload if the answer
--       changed (at most one reload per MIN_GAP s, postponed not dropped);
--    d) a diagnostic log of every load, event and decision.
--    Any error or doubt: the panel stays / comes ON.
local PANELS = { "eDP-1" }
local KEPT_WITH = { "Samsung Electric Company LS27FG53x H9DL300352" }

local RUNDIR = os.getenv("XDG_RUNTIME_DIR") or "/tmp"
local LOGFILE = RUNDIR .. "/displayctl-monitors.log"
local GONE_FILE = RUNDIR .. "/displayctl-gone"
local STAMP = RUNDIR .. "/displayctl-reload-stamp"
local MIN_GAP, GONE_TTL, LOG_MAX = 5, 30, 262144

local function log(msg)
  pcall(function()
    local mode = "a"
    local f = io.open(LOGFILE, "r")
    if f then
      local size = f:seek("end")
      f:close()
      if size and size > LOG_MAX then mode = "w" end
    end
    f = io.open(LOGFILE, mode)
    if f then f:write(os.date("%H:%M:%S"), " [", tostring(os.time()), "] ", msg, "\n"); f:close() end
  end)
end

local function field(m, key)
  local ok, v = pcall(function() return m[key] end)
  if ok then return v end
  return nil
end

local function is_panel(name)
  if type(name) ~= "string" then return false end
  return name:match("^eDP%-") ~= nil or name:match("^LVDS%-") ~= nil
      or name:match("^DSI%-") ~= nil
end

local function is_real(name)  -- a physical monitor, not Hyprland's placeholder
  return type(name) == "string" and name ~= "FALLBACK" and name:match("^HEADLESS%-") == nil
end

local function is_kept(desc)
  if type(desc) ~= "string" then return false end
  for _, want in ipairs(KEPT_WITH) do
    if desc == want then return true end
  end
  return false
end

-- "Gone" memory: kept-with monitors unplugged in the last GONE_TTL seconds.
local function read_gone()
  local gone = {}
  pcall(function()
    local f = io.open(GONE_FILE, "r")
    if not f then return end
    for line in f:lines() do
      local t, desc = line:match("^(%d+)\t(.*)$")
      if t and os.time() - tonumber(t) < GONE_TTL then gone[desc] = tonumber(t) end
    end
    f:close()
  end)
  return gone
end

local function write_gone(gone)
  pcall(function()
    local f = io.open(GONE_FILE, "w")
    if not f then return end
    for desc, t in pairs(gone) do f:write(tostring(t), "\t", desc, "\n") end
    f:close()
  end)
end

local function monitors()
  local ok, ms = pcall(hl.get_monitors)
  if ok and type(ms) == "table" then return ms end
  return {}
end

local function describe_monitors()
  local parts = {}
  for _, m in ipairs(monitors()) do
    table.insert(parts, tostring(field(m, "name")) .. "=" .. tostring(field(m, "description")))
  end
  return "[" .. table.concat(parts, "; ") .. "]"
end

local function kept_with_present()
  local gone = read_gone()
  for _, m in ipairs(monitors()) do
    local name, desc = field(m, "name"), field(m, "description")
    local is_gone = gone[desc] or gone["port:" .. tostring(name)] or gone["*"]
    if is_real(name) and not is_panel(name) and is_kept(desc) and not is_gone then
      return true
    end
  end
  return false
end

local function real_monitors_on()
  local n = 0
  for _, m in ipairs(monitors()) do
    if is_real(field(m, "name")) then n = n + 1 end
  end
  return n
end

local function panel_listed()
  for _, m in ipairs(monitors()) do
    local name = field(m, "name")
    for _, p in ipairs(PANELS) do
      if name == p then return true end
    end
  end
  return false
end

-- Load-time decision.
local okp, present = pcall(kept_with_present)
local PANELS_OFF = (okp and present == true)
if PANELS_OFF then
  for _, panel in ipairs(PANELS) do
    hl.monitor({ output = panel, disabled = true })
  end
end
log("load: monitors " .. describe_monitors() .. " -> panel " .. (PANELS_OFF and "OFF" or "on"))

-- Timers and reloads.
local timers = {}

local function after(ms, fn)
  local ok = pcall(function()
    local t
    t = hl.timer(function()
      pcall(function() t:set_enabled(false) end)
      pcall(fn)
    end, { timeout = ms, type = "repeat" })
    table.insert(timers, t)
  end)
  if not ok then pcall(fn) end  -- no timers available: act right away
end

local function seconds_since_reload()
  local ok, n = pcall(function()
    local f = io.open(STAMP, "r")
    if not f then return nil end
    local v = tonumber(f:read("*l"))
    f:close()
    return v
  end)
  if not ok or not n then return MIN_GAP end
  return os.time() - n
end

local function request_reload(reason)
  local since = seconds_since_reload()
  if since < MIN_GAP then
    log("reload postponed (" .. reason .. "), last reload " .. since .. " s ago")
    after((MIN_GAP - since) * 1000 + 100, function() request_reload(reason) end)
    return
  end
  pcall(function()
    local f = io.open(STAMP, "w")
    if f then f:write(tostring(os.time()), "\n"); f:close() end
  end)
  log("reload (" .. reason .. ")")
  hl.dispatch(hl.dsp.reload_config())
end

local function enable_panels_now(reason)
  for _, panel in ipairs(PANELS) do
    local ok = pcall(hl.monitor, { output = panel, mode = "preferred", position = "auto", scale = 1 })
    log("panel " .. panel .. " ON directly (" .. reason .. ")" .. (ok and "" or " [hl.monitor failed]"))
  end
  -- If the direct rule didn't take effect, reload (the load then honours the
  -- "gone" memory, so it won't turn the panel off again).
  after(1000, function()
    if not panel_listed() then request_reload("panel still off after direct enable") end
  end)
end

local function recheck(reason)
  local okw, want = pcall(kept_with_present)
  want = (okw and want == true)
  local real = real_monitors_on()
  log("check (" .. reason .. "): monitors " .. describe_monitors() .. ", kept-with present "
      .. tostring(want) .. ", real monitors on " .. real .. ", loaded with panel "
      .. (PANELS_OFF and "OFF" or "on"))
  if real == 0 then  -- invariant: never zero screens
    enable_panels_now("no real monitor on")
    return
  end
  if want ~= PANELS_OFF then request_reload(reason) end
end

-- When a "gone" entry expires nothing else may happen (e.g. an unreadable
-- replug couldn't clear "*"), so re-check just after each entry runs out.
-- One timer per entry; a reload destroys them, but the load schedules again.
local function recheck_when_memory_expires()
  for key, t in pairs(read_gone()) do
    local left = t + GONE_TTL - os.time()
    after(math.max(left, 0) * 1000 + 1000, function()
      recheck("gone memory expired: " .. key)
    end)
  end
end

-- Handlers.
local function on_removed(m)
  local name, desc = field(m, "name"), field(m, "description")
  log("event monitor.removed " .. tostring(name) .. " = " .. tostring(desc))
  if is_panel(name) then return end  -- our own panel switching
  if is_kept(desc) or desc == nil or name == nil then
    -- Decide from the event itself: don't wait for hl.get_monitors to catch up.
    -- Remember it as gone by the best key the event gives us. Without this, a
    -- reload while hl.get_monitors is still stale would turn the panel off
    -- again (the L11 failure). A wrong guess only keeps an extra screen on.
    local key = desc or (name and ("port:" .. name)) or "*"
    local gone = read_gone(); gone[key] = os.time(); write_gone(gone)
    log("remembered as gone: " .. key)
    recheck_when_memory_expires()
    if PANELS_OFF then enable_panels_now("kept-with monitor removed") end
  end
  after(1000, function() recheck("1 s after removal") end)
  after(3000, function() recheck("3 s after removal") end)
end

local function on_added(m)
  local name, desc = field(m, "name"), field(m, "description")
  log("event monitor.added " .. tostring(name) .. " = " .. tostring(desc))
  if is_panel(name) then return end
  if is_kept(desc) then  -- it's back: forget every way we remembered it
    local gone = read_gone()
    gone[desc] = nil; gone["port:" .. tostring(name)] = nil; gone["*"] = nil
    write_gone(gone)
  end
  after(1000, function() recheck("1 s after addition") end)
  after(3000, function() recheck("3 s after addition") end)
end

pcall(hl.on, "monitor.added", on_added)
pcall(hl.on, "monitor.removed", on_removed)

-- After every load: re-check once things have settled (also enforces the
-- "never zero screens" invariant after a reload).
after(2500, function() recheck("2.5 s after load") end)
recheck_when_memory_expires()
